package com.siral.utils

enum class Actions {
    LOGIN,
    INSERT_NEW_ROLE,
    DELETE_ROLE,
    INSERT_DINNING_HALL,
    DELETE_DINNING_HALL,
    MAKE_RESERVATION,
    DELETE_RESERVATION,
    INSERT_SCHEDULE_ITEM,
    DELETE_SCHEDULE_ITEM,
}