package com.siral.utils

import kotlinx.serialization.Serializable

@Serializable
enum class ResponseMessage {
    INVALID_CREDENTIALS,
    INVALID_STUDENT,
    ACCESS_DENIED,
    MISSING_REQUIRED_FIELDS,
    DINNING_HALL_NOT_FOUND,
    INVALID_ROLE,
    USER_ALREADY_HAS_ROLE,
    USER_INSERTED_SUCCESSFULLY,
    MISSING_EMAIL,
    USER_NOT_FOUND,
    USER_DELETED_SUCCESSFULLY,
    MISSING_DINNING_HALL_NAME,
    DINNING_HALL_ALREADY_EXISTS,
    DINNING_HALL_INSERTED_SUCCESSFULLY,
    DINNING_HALL_DELETED_SUCCESSFULLY,
    MISSING_SCHEDULE_ITEM_ID,
    MEAL_ALREADY_RESERVED,
    SCHEDULE_ITEM_NOT_FOUND,
    SCHEDULE_ITEM_NOT_AVAILABLE,
    RESERVATION_MADE,
    MISSING_RESERVATION_ID,
    RESERVATION_DELETED,
    INVALID_DATE,
    ALL_DONE,
    MISSING_STUDENT_ID,
    RESERVATION_NOT_FOUND,
    INVALID_DAYS
}